'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Alumno
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Matricula As Nullable(Of Integer)

End Class
