'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class EscuelaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=EscuelaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AlumnoMaterias() As DbSet(Of AlumnoMateria)
    Public Overridable Property Alumnos() As DbSet(Of Alumno)
    Public Overridable Property Materias() As DbSet(Of Materia)
    Public Overridable Property Usuarios() As DbSet(Of Usuario)

End Class
